### ISSUE TITLE
Windows issue: _slangtorch_texture_baker error when starting gradio

### ISSUE THREAD

**Issue by SoftologyPro** [Stability-AI/stable-fast-3d#13]
When I start gradio_app.py I get this

```
Traceback (most recent call last):
  File "D:\Tests\StableFast3D\stable-fast-3d\gradio_app.py", line 43, in <module>
    model = SF3D.from_pretrained(
  File "D:\Tests\StableFast3D\stable-fast-3d\sf3d\system.py", line 89, in from_pretrained
    model = cls(cfg)
  File "D:\Tests\StableFast3D\stable-fast-3d\sf3d\models\utils.py", line 29, in __init__
    self.configure(*args, **kwargs)
  File "D:\Tests\StableFast3D\stable-fast-3d\sf3d\system.py", line 139, in configure
    self.baker = TextureBaker()
  File "D:\Tests\StableFast3D\stable-fast-3d\sf3d\texture_baker.py", line 13, in __init__
    self.baker = slangtorch.loadModule(
  File "D:\Tests\StableFast3D\stable-fast-3d\venv\lib\site-packages\slangtorch\slangtorch.py", line 617, in loadModule
    rawModule = _loadModule(fileName, moduleName, buildDir, options, sourceDir=outputFolder, verbose=verbose, includePaths=includePaths, dryRun=False)
  File "D:\Tests\StableFast3D\stable-fast-3d\venv\lib\site-packages\slangtorch\slangtorch.py", line 536, in _loadModule
    slangLib, metadata = compileAndLoadModule(
  File "D:\Tests\StableFast3D\stable-fast-3d\venv\lib\site-packages\slangtorch\slangtorch.py", line 427, in compileAndLoadModule
    slangLib = _compileAndLoadModule(metadata, sources, moduleName, buildDir, slangSourceDir, verbose)
  File "D:\Tests\StableFast3D\stable-fast-3d\venv\lib\site-packages\slangtorch\slangtorch.py", line 466, in _compileAndLoadModule
    return jit_compile(
  File "D:\Tests\StableFast3D\stable-fast-3d\venv\lib\site-packages\slangtorch\util\compile.py", line 93, in jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Tests\StableFast3D\stable-fast-3d\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2132, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _slangtorch_texture_baker_44136fa355b3678a: The specified module could not be found.
```

Any ideas?

**Comment by FishGPT** [comment]
You can try reinstall gradio, before: pip cache purge

**Comment by 945222256** [comment]
cf same issue

**Comment by 945222256** [comment]
> You can try reinstall gradio, before: pip cache purge

not working.

python run.py demo_files/examples/chair1.png --output-dir output/      get same feedback

**Comment by ouceduxzk** [comment]
the slangtroch dont have mac version, it has both windows and unix library, but lacks mac verison, that's why it fails on my mac

**Comment by SoftologyPro** [comment]
I am running this on Windows.

**Comment by geoffreyvilcot** [comment]
I have the same issue on windows, I fix it by installing the right version of pytorch according to my cuda version.

**Comment by SoftologyPro** [comment]
> I have the same issue on windows, I fix it by installing the right version of pytorch according to my cuda version.

Thanks, that works.  I must have had an incorrect torch version installed.
To make it easier for other Windows users, here is a batch file you can run in an empty directory to do the install.

```
@echo off

echo *** %time% *** Deleting stable-fast-3d directory if it exists
if exist stable-fast-3d\. rd /S /Q stable-fast-3d

echo *** %time% *** Cloning stable-fast-3d repository
git clone https://github.com/Stability-AI/stable-fast-3d
cd stable-fast-3d

echo *** %time% *** Creating venv
python -m venv venv

echo *** %time% *** Activating venv
call venv\scripts\activate.bat

echo *** %time% *** Installing requirments
python -m pip install --upgrade pip
pip install wheel
pip install matplotlib==3.9.0
pip install -r requirements.txt
pip install -r requirements-demo.txt
pip install --upgrade huggingface_hub

echo *** %time% *** Patching xformers
pip uninstall -y xformers
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121

echo *** %time% *** Installing GPU torch
pip uninstall -y torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.4.0+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
pip uninstall -y charset-normalizer
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts charset-normalizer==3.3.2
pip uninstall -y numpy
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts numpy==1.26.4

call venv\scripts\deactivate.bat
cd ..
echo *** %time% *** Finished stable-fast-3d install
echo.
pause
```

When I click the first leftb most animal character I get an error

```
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4598657: character maps to <undefined>
```

The next sample seems OK without an error.  But once I select the racoon and pick triangle meshing, then click Run I get this stats
```
Already has alpha
Generation took: 1.6904230117797852 s
Peak Memory: 6118.591796875 MB
```
but nothing shows up in the 3D model area.

I must still be missing something.

**Comment by clearsitedesigns** [comment]
Same issue on a mac 1pro max

**Comment by jammm** [comment]
There's no mac support yet.

**Comment by SoftologyPro** [comment]
OK, got it working here.  For other Windows users who want to run locally, here is an install.bat that you save and run inside an empty diretcory.

```
@echo off

echo *** %time% *** Deleting stable-fast-3d directory if it exists
if exist stable-fast-3d\. rd /S /Q stable-fast-3d

echo *** %time% *** Cloning stable-fast-3d repository
git clone https://github.com/Stability-AI/stable-fast-3d
cd stable-fast-3d

echo *** %time% *** Creating venv
python -m venv venv

echo *** %time% *** Activating venv
call venv\scripts\activate.bat

echo *** %time% *** Installing requirments
python -m pip install --upgrade pip
pip install wheel
pip install matplotlib==3.9.0
pip install -r requirements.txt
pip install -r requirements-demo.txt
pip install --upgrade huggingface_hub

echo *** %time% *** Patching xformers
pip uninstall -y xformers
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121

echo *** %time% *** Installing GPU torch
pip uninstall -y torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.4.0+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

call venv\scripts\deactivate.bat
cd ..
echo *** %time% *** Finished stable-fast-3d install
echo.
echo Check the stats for any errors.  Do not assume it worked.
pause
```

Once installed, save this run.bat in the same directory as install.bat and run it to start the gradio UI.

```
@echo off
cls
cd stable-fast-3d
call venv\scripts\activate.bat
huggingface-cli login --token <PUT YOUR HUGGINGFACE READ TOKEN HERE>
python  -X utf8 gradio_app.py
call venv\scripts\deactivate.bat
cd..
```

![image](https://github.com/user-attachments/assets/60215778-183a-49e8-b086-96c358eab155)

**Comment by th3redmage** [comment]
adding X utf8 before the gradio for me was key to making this work, thank you

**Comment by vork** [comment]
We've recently replaced the baker from slang to a native CUDA/CPP/Metal one. Please pull the changes and test again.
