### ISSUE TITLE
Trouble running model | CreateProcess failed: The system cannot find texture_baker_cuda.cuda.o

### ISSUE THREAD

**Issue by JinseiSteven** [Stability-AI/stable-fast-3d#25]
I'm currently trying to run manual inference using the example image, however every time i run the code i get the following error. I have had CUDA issues before this, but I thought to have resolved it by: purging all existing CUDA files etc and installing the version which is compatible with my graphics card and also with my pytorch version.
When i run `python  -X utf8 gradio_app.py` I also get the exact same error.

- Win 10 x64
- GTX1080
- Python 3.11.9
- CUDA 12.1
- Torch 2.4.0+121

```(venv) D:\BladeRunner_Project\stable-fast-3d>python run.py demo_files/examples/chair1.png --output-dir output/
D:\BladeRunner_Project\stable-fast-3d\sf3d\models\network.py:68: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)
D:\BladeRunner_Project\stable-fast-3d\sf3d\models\network.py:74: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\open_clip\factory.py:128: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=map_location)
D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\utils\cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "C:\Users\hcilabstudent.4180L-93202\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\BladeRunner_Project\stable-fast-3d\run.py", line 71, in <module>
    model = SF3D.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\sf3d\system.py", line 89, in from_pretrained
    model = cls(cfg)
            ^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\sf3d\models\utils.py", line 29, in __init__
    self.configure(*args, **kwargs)
  File "D:\BladeRunner_Project\stable-fast-3d\sf3d\system.py", line 139, in configure
    self.baker = TextureBaker()
                 ^^^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\sf3d\texture_baker.py", line 13, in __init__
    self.baker = slangtorch.loadModule(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\slangtorch\slangtorch.py", line 617, in loadModule
    rawModule = _loadModule(fileName, moduleName, buildDir, options, sourceDir=outputFolder, verbose=verbose, includePaths=includePaths, dryRun=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\slangtorch\slangtorch.py", line 536, in _loadModule
    slangLib, metadata = compileAndLoadModule(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\slangtorch\slangtorch.py", line 427, in compileAndLoadModule
    slangLib = _compileAndLoadModule(metadata, sources, moduleName, buildDir, slangSourceDir, verbose)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\slangtorch\slangtorch.py", line 466, in _compileAndLoadModule
    return jit_compile(
           ^^^^^^^^^^^^
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\slangtorch\util\compile.py", line 71, in jit_compile
    _write_ninja_file_and_build_library(
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_slangtorch_texture_baker_44136fa355b3678a': [1/3] C:\"Program Files"\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output texture_baker_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_slangtorch_texture_baker_44136fa355b3678a -DTORCH_API_INCLUDE_EXTENSION_H -ID:\BladeRunner_Project\stable-fast-3d\sf3d -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include\TH -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include\THC "-IC:\"Program Files"\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IC:\Users\hcilabstudent.4180L-93202\AppData\Local\Programs\Python\Python311\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17 --std=c++17 -c D:\BladeRunner_Project\stable-fast-3d\sf3d\.slangtorch_cache\texture_baker\44136fa355b3678a\texture_baker_cuda.cu -o texture_baker_cuda.cuda.o
FAILED: texture_baker_cuda.cuda.o
C:\"Program Files"\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output texture_baker_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_slangtorch_texture_baker_44136fa355b3678a -DTORCH_API_INCLUDE_EXTENSION_H -ID:\BladeRunner_Project\stable-fast-3d\sf3d -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include\TH -ID:\BladeRunner_Project\stable-fast-3d\venv\Lib\site-packages\torch\include\THC "-IC:\"Program Files"\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IC:\Users\hcilabstudent.4180L-93202\AppData\Local\Programs\Python\Python311\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDAninja: fatal: ReadFile: The handle is invalid.

_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17 --std=c++17 -c D:\BladeRunner_Project\stable-fast-3d\sf3d\.slangtorch_cache\texture_baker\44136fa355b3678a\texture_baker_cuda.cu -o texture_baker_cuda.cuda.o
CreateProcess failed: The system cannot find the file specified.```

**Comment by heonbert** [comment]
This issue is caused by NVCC failing to compile. If your account name contains non-ASCII characters (such as Korean, Chinese, or Japanese) in a Windows environment, try using an account with only ASCII characters.

If that doesn’t resolve the issue, try installing Visual Studio 2022 version 17.8 instead of the latest version (currently 17.11).

**Comment by vork** [comment]
We recently pushed a small update which gets rid of the slang-based baker. Try pulling the latest changes.
