### ISSUE TITLE
ValueError('num_channels must be divisible by num_groups')

### ISSUE THREAD

**Issue by Lucalme** [Stability-AI/stable-fast-3d#32]
I tried reinstalling my venv, deleting the folder altogether and restarting from scratch but this message keeps poping whenever I launch either the app or just the run script.
I already had success running the run.py, not sure about the app. But I must have messed up somewhere so it does not work anymore.

here's the callback for reference

>(venv) PS E:\Softs\AI Stuff\Stability AI\stable-fast-3d> python run.py demo_files/examples/chair1.png --output-dir output/
Traceback (most recent call last):
  File "E:\Softs\AI Stuff\Stability AI\stable-fast-3d\run.py", line 71, in <module>
    model = SF3D.from_pretrained(
  File "E:\Softs\AI Stuff\Stability AI\stable-fast-3d\sf3d\system.py", line 89, in from_pretrained
    model = cls(cfg)
  File "E:\Softs\AI Stuff\Stability AI\stable-fast-3d\sf3d\models\utils.py", line 29, in __init__
    self.configure(*args, **kwargs)
  File "E:\Softs\AI Stuff\Stability AI\stable-fast-3d\sf3d\system.py", line 105, in configure
    self.backbone = find_class(self.cfg.backbone_cls)(self.cfg.backbone)
  File "E:\Softs\AI Stuff\Stability AI\stable-fast-3d\sf3d\models\utils.py", line 29, in __init__
    self.configure(*args, **kwargs)
  File "E:\Softs\AI Stuff\Stability AI\stable-fast-3d\sf3d\models\transformers\backbone.py", line 430, in configure
    self.norm_triplane = torch.nn.GroupNorm(
  File "E:\Softs\AI Stuff\Stability AI\venv\lib\site-packages\torch\nn\modules\normalization.py", line 267, in __init__
    raise ValueError('num_channels must be divisible by num_groups')
ValueError: num_channels must be divisible by num_groups

**Comment by Lucalme** [comment]
Nevermind, I think I just forgot to login into huggingface again when i changed my HF_HOME env path.
