### ISSUE TITLE
Error when call function SF3D.from_pretrained

### ISSUE THREAD

**Issue by Minhtrna** [Stability-AI/stable-fast-3d#44]
I got the error message: FileNotFoundError: [WinError 2] The system cannot find the file specified. 
The error message indicates that issuse in :
 `model = SF3D.from_pretrained(
 "stabilityai/stable-fast-3d",
 config_name="config.yaml",
 weight_name="model.safetensors",`
I have logged into huggingface with a token so the error cannot come from not logging in, I have also taken access from huggingface, recreate new env and try again but still not work. Any solution for this?

**Comment by Minhtrna** [comment]
Ok i followed some instruction on internet to add `shell=True` in `result = subprocess.run([vswhere_path, '-latest', '-property', 'installationPath'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)` a line of `find_cl()` function in slangtorch.py. 
Now the error become 

> Traceback (most recent call last):
  File "C:\Mlab-Project\Github\stable-fast-3d\app.py", line 32, in <module>
    model = SF3D.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Mlab-Project\Github\stable-fast-3d\sf3d\system.py", line 89, in from_pretrained
    model = cls(cfg)
            ^^^^^^^^
  File "C:\Mlab-Project\Github\stable-fast-3d\sf3d\models\utils.py", line 29, in __init__
    self.configure(*args, **kwargs)
  File "C:\Mlab-Project\Github\stable-fast-3d\sf3d\system.py", line 139, in configure
    self.baker = TextureBaker()
                 ^^^^^^^^^^^^^^
  File "C:\Mlab-Project\Github\stable-fast-3d\sf3d\texture_baker.py", line 13, in __init__
    self.baker = slangtorch.loadModule(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\quang\anaconda3\envs\test\Lib\site-packages\slangtorch\slangtorch.py", line 617, in loadModule
    rawModule = _loadModule(fileName, moduleName, buildDir, options, sourceDir=outputFolder, verbose=verbose, includePaths=includePaths, dryRun=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\quang\anaconda3\envs\test\Lib\site-packages\slangtorch\slangtorch.py", line 536, in _loadModule
    slangLib, metadata = compileAndLoadModule(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\quang\anaconda3\envs\test\Lib\site-packages\slangtorch\slangtorch.py", line 427, in compileAndLoadModule
    slangLib = _compileAndLoadModule(metadata, sources, moduleName, buildDir, slangSourceDir, verbose)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\quang\anaconda3\envs\test\Lib\site-packages\slangtorch\slangtorch.py", line 447, in _compileAndLoadModule
    _add_msvc_to_env_var()
  File "C:\Users\quang\anaconda3\envs\test\Lib\site-packages\slangtorch\slangtorch.py", line 83, in _add_msvc_to_env_var
    path_to_add = find_cl()
                  ^^^^^^^^^
  File "C:\Users\quang\anaconda3\envs\test\Lib\site-packages\slangtorch\slangtorch.py", line 74, in find_cl
    raise ValueError("cl.exe not found in default Visual Studio installation path")
ValueError: cl.exe not found in default Visual Studio installation path

seem to be i need the c++ build tools to beable to load the model. But it still run fine on google colab. why it's cannot on local machine :(
