### ISSUE TITLE
failed to compile uv_unwrapper 

### ISSUE THREAD

**Issue by trackme518** [Stability-AI/stable-fast-3d#49]
Hi,
I can't compile uv_unwrapper. Main culprint:

```
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:45:19: error: ‘exchange’ is not a member of ‘std’
   45 |     : triIdx(std::exchange(other.triIdx, nullptr)),

```
Full error:

```
(env) glass@glass-HP-Z4-G4-Workstation:~/python/stable-fast-3d/uv_unwrapper$ python3 setup.py build
[<setuptools.extension.Extension('uv_unwrapper._C') at 0x752116d0fcb0>]
running build
running build_py
copying uv_unwrapper/__init__.py -> build/lib.linux-x86_64-cpython-312/uv_unwrapper
copying uv_unwrapper/unwrap.py -> build/lib.linux-x86_64-cpython-312/uv_unwrapper
running build_ext
building 'uv_unwrapper._C' extension
Emitting ninja build file /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/bvh.o.d -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/home/glass/python/env/lib/python3.12/site-packages/torch/include -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/TH -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/THC -I/home/glass/python/env/include -I/usr/include/python3.12 -c -c /home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp -o /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/bvh.o -O3 -fdiagnostics-color=always -fopenmp -march=native -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
FAILED: /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/bvh.o 
c++ -MMD -MF /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/bvh.o.d -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/home/glass/python/env/lib/python3.12/site-packages/torch/include -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/TH -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/THC -I/home/glass/python/env/include -I/usr/include/python3.12 -c -c /home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp -o /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/bvh.o -O3 -fdiagnostics-color=always -fopenmp -march=native -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp: In constructor ‘UVUnwrapper::BVH::BVH(UVUnwrapper::Triangle*, int*, const size_t&)’:
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:25:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct UVUnwrapper::BVHNode’; use assignment or value-initialization instead [-Wclass-memaccess]
   25 |   memset(bvhNode, 0, triCount * 2 * sizeof(BVHNode));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:3:
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.h:75:20: note: ‘struct UVUnwrapper::BVHNode’ declared here
   75 | struct alignas(32) BVHNode {
      |                    ^~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:28:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
   28 |   for (int i = 0; i < triCount; i++)
      |                   ~~^~~~~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp: In constructor ‘UVUnwrapper::BVH::BVH(UVUnwrapper::BVH&&)’:
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:45:19: error: ‘exchange’ is not a member of ‘std’
   45 |     : triIdx(std::exchange(other.triIdx, nullptr)),
      |                   ^~~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:8:1: note: ‘std::exchange’ is defined in header ‘<utility>’; did you forget to ‘#include <utility>’?
    7 | #include <queue>
  +++ |+#include <utility>
    8 | #include <tuple>
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:46:22: error: ‘exchange’ is not a member of ‘std’
   46 |       actualIdx(std::exchange(other.actualIdx, nullptr)),
      |                      ^~~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:46:22: note: ‘std::exchange’ is defined in header ‘<utility>’; did you forget to ‘#include <utility>’?
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:47:21: error: ‘exchange’ is not a member of ‘std’
   47 |       triangle(std::exchange(other.triangle, nullptr)),
      |                     ^~~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:47:21: note: ‘std::exchange’ is defined in header ‘<utility>’; did you forget to ‘#include <utility>’?
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:48:20: error: ‘exchange’ is not a member of ‘std’
   48 |       bvhNode(std::exchange(other.bvhNode, nullptr)) {}
      |                    ^~~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:48:20: note: ‘std::exchange’ is defined in header ‘<utility>’; did you forget to ‘#include <utility>’?
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.h:115:13: warning: ‘UVUnwrapper::BVH::triangle’ will be initialized after [-Wreorder]
  115 |   Triangle *triangle = nullptr;
      |             ^~~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.h:114:12: warning:   ‘UVUnwrapper::BVHNode* UVUnwrapper::BVH::bvhNode’ [-Wreorder]
  114 |   BVHNode *bvhNode = nullptr;
      |            ^~~~~~~
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/bvh.cpp:44:1: warning:   when initialized here [-Wreorder]
   44 | BVH::BVH(BVH &&other) noexcept // move constructor
      | ^~~
[2/2] c++ -MMD -MF /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/unwrapper.o.d -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/home/glass/python/env/lib/python3.12/site-packages/torch/include -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/TH -I/home/glass/python/env/lib/python3.12/site-packages/torch/include/THC -I/home/glass/python/env/include -I/usr/include/python3.12 -c -c /home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/unwrapper.cpp -o /home/glass/python/stable-fast-3d/uv_unwrapper/build/temp.linux-x86_64-cpython-312/uv_unwrapper/csrc/unwrapper.o -O3 -fdiagnostics-color=always -fopenmp -march=native -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/unwrapper.cpp: In function ‘void UVUnwrapper::perform_intersection_check(BVH*, int, Triangle*, uv_float3*, int64_t*, ssize_t, int, std::vector<std::set<int> >&)’:
/home/glass/python/stable-fast-3d/uv_unwrapper/uv_unwrapper/csrc/unwrapper.cpp:91:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   91 |   for (int idx = 0; idx < unique_intersections.size(); idx++) {
      |                     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/glass/python/env/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/glass/python/stable-fast-3d/uv_unwrapper/setup.py", line 69, in <module>
    setup(
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/glass/python/env/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
    build_ext.build_extensions(self)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/glass/python/env/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glass/python/env/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/glass/python/env/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/glass/python/env/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
(env) glass@glass-HP-Z4-G4-Workstation:~/python/stable-fast-3d/uv_unwrapper$ 
```

**Comment by trackme518** [comment]
I am running Python 3.12, CUDA 12.4, torch 2.4.1+cu124, I have installed ninja, cmake and gcc g++ and set USE_CUDA=1

**Comment by trackme518** [comment]
I have solved this by modifying bhv.cpp by adding line:
`
#include <utility>
`

**Comment by Utopiah** [comment]
Mean `bvh.cpp`

**Comment by jammm** [comment]
Which version of GCC are you using @trackme518  ?

**Comment by qiaodongxing** [comment]
> I have solved this by modifying bhv.cpp by adding line: `#include <utility>`

it works well for me
