### ISSUE TITLE
UnicodeDecodeError:

### ISSUE THREAD

**Issue by jaehyunshinML** [Stability-AI/stable-fast-3d#5]
Hi 
I tired to run in local with gradio_app.py.
I've got this error.

Generation took: 4.131814479827881 s
Peak Memory: 8355.408203125 MB
ERROR:    Exception in ASGI application
  File "/home/xxxx/miniconda3/envs/pytorch2/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1932325: ordinal not in range(128)

**Comment by vork** [comment]
Can you try running with `python -X utf8`?

**Comment by FishGPT** [comment]
> Hi I tired to run in local with gradio_app.py. I've got this error.
> 
> Generation took: 4.131814479827881 s Peak Memory: 8355.408203125 MB ERROR: Exception in ASGI application File "/home/xxxx/miniconda3/envs/pytorch2/lib/python3.10/encodings/ascii.py", line 26, in decode return codecs.ascii_decode(input, self.errors)[0] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1932325: ordinal not in range(128)

I have same error, after reinstall gradio...success🤔

**Comment by Limbicnation** [comment]
Hi, I get the same error when running the Gradio app with:

`python -X utf8 gradio_app.py`

```
To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/../anaconda3/envs/fast3d/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/../anaconda3/envs/fast3d/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__
```

Ubuntu 24.04.1 LTS

**Comment by Limbicnation** [comment]
Resolved by upgrading:
```
pip install --upgrade pydantic
pip install --upgrade gradio
```

Run:
```bash
python -Xutf8 gradio_app.py
```
