### ISSUE TITLE
Error in gradio app when loading Input image

### ISSUE THREAD

**Issue by mtsnrtkhr** [Stability-AI/stable-fast-3d#50]
# Environment: 
OS:Windows11 (Japanese)
Python: 3.12.4
CUDA:12.4
Pytorch:2.4.1+cu124
Browser: Edge, Chrome, FireFox

# Error from Browser Dev Tool
When I start gradio app by ```python gradio_app.py```, 
I can access to "http://127.0.0.1:7861/"
When I try to use Example, it cause error on the browser (Edge)
"Could not parse server response: SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON" 

This is caused by the Status below.

Request URL: http://127.0.0.1:7861/run/predict
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:7861
Referrer Policy: strict-origin-when-cross-origin

# Error from Terminal
(.venv) PS C:\Users\Programming\stable-fast-3d> python gradio_app.py
Deleting /tmp\gradio
C:\Users\Programming\stable-fast-3d\sf3d\models\network.py:22: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  return decorator_with_args(*args, **kwargs)(fn)
C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\open_clip\factory.py:128: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=map_location)       
C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\gradio_client\utils.py:1097: UserWarning: file() is deprecated and will be removed in a future version. Use handle_file() instead.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\gradio\route_utils.py", line 733, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\gradio\route_utils.py", line 749, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)  
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 656, in solve_dependencies     
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 881, in request_body_to_args   
    fields_to_extract = get_cached_model_fields(first_field.type_)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\_compat.py", line 285, in get_model_fields
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler  
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>     
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type   
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type   
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Programming\stable-fast-3d\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

# Difference from Original

The difference from original file is that the version of gpytoolbox in the requirements.txt. I have changed it form gpytoolbox==0.2.0 to gpytoolbox==0.3.2 because of the install error.

**Comment by oliverban** [comment]
I get this error as well, any fix you found?

**Comment by mtsnrtkhr** [comment]
@oliverban 
Thank you for your information!
When I run
`pip install --upgrade gradio`
gradio was updated to 4.44.1 from 4.41.0 as below.
> Installing collected packages: gradio
>   Attempting uninstall: gradio
>     Found existing installation: gradio 4.41.0
>     Uninstalling gradio-4.41.0:
>       Successfully uninstalled gradio-4.41.0
> Successfully installed gradio-4.44.1
And the error has been solved!!

I can run the app with
`python -Xutf8 gradio_app.py`
or
`$env:PYTHONUTF8 = "1"; python gradio_app.py`
but
`python gradio_app.py`
also works without unicode error for me.

Additional infrormation'
For pydantic, which was mentioned in #5, it was not updated as below.
`pip install --upgrade pydantic`
> Requirement already satisfied: pydantic in c:\users\programming\stable-fast-3d\.venv\lib\site-packages (2.9.2)
> Requirement already satisfied: annotated-types>=0.6.0 in c:\users\programming\stable-fast-3d\.venv\lib\site-packages (from pydantic) (0.7.0)
> Requirement already satisfied: pydantic-core==2.23.4 in c:\users\programming\stable-fast-3d\.venv\lib\site-packages (from pydantic) (2.23.4)
> Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\programming\stable-fast-3d\.venv\lib\site-packages (from pydantic) (4.9.0)

**Comment by qiaodongxing** [comment]
change the all  path  line in  gradio_app.py 
such as 
"demo_files/examples" ---> "./demo_files/examples"
