### ISSUE TITLE
unable to build wheel for gpytoolbox

### ISSUE THREAD

**Issue by bishibishibi** [Stability-AI/stable-fast-3d#54]
I had problems when running requirements.txt
`Building wheels for collected packages: gpytoolbox, texture_baker, uv_unwrapper
  Building wheel for gpytoolbox (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for gpytoolbox (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [187 lines of output]
      /tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/__init__.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/adjacency_matrix.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/angle_defect.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/angle_defect_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/apply_colormap.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/approximate_hausdorff_distance.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/array_correspondence.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/bad_quad_mesh_from_quadtree.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/barycenters.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/barycentric_coordinates.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/biharmonic_energy.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/biharmonic_energy_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/boundary_edges.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/boundary_faces.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/boundary_loops.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/boundary_vertices.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/catmull_rom_spline.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/colormap.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/compactly_supported_normal.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/compactly_supported_normal_kernel.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cone.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/connected_components.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cotangent_laplacian.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cotangent_laplacian_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cotangent_weights.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cotangent_weights_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cut_edges.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/cylinder.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/decimate.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/doublearea.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/doublearea_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/edge_edge_distance.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/edge_indices.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/edges.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/faces.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/fast_winding_number.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/fd_grad.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/fd_interpolate.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/fd_partial_derivative.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/fixed_dof_solve.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/gaussian_process.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/grad.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/grad_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/grid_laplacian_eigenfunctions.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/grid_neighbors.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/halfedge_edge_map.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/halfedge_lengths.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/halfedge_lengths_squared.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/halfedges.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/halffaces.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/icosphere.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/in_element_aabb.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/in_quadtree.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/initialize_aabbtree.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/initialize_quadtree.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/linear_blend_skinning.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/linear_elasticity.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/linear_elasticity_stiffness.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/marching_cubes.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/marching_squares.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/massmatrix.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/massmatrix_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/matrix_from_function.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/metropolis_hastings.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/min_quad_with_fixed.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/minimum_distance.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/non_manifold_edges.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/normalize_points.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/offset_surface.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/particle_swarm.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/per_face_normals.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/per_vertex_normals.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/png2poly.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/poisson_surface_reconstruction.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/quadtree_boundary.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/quadtree_children.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/quadtree_gradient.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/quadtree_laplacian.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/random_points_on_mesh.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/ray_box_intersect.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/ray_mesh_intersect.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/ray_polyline_intersect.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/ray_triangle_intersect.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/reach_for_the_spheres.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/read_dmat.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/read_mesh.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/regular_circle_polyline.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/regular_cube_mesh.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/regular_square_mesh.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/remesh_botsch.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/remove_duplicate_vertices.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/remove_unreferenced.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/signed_distance.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/signed_distance_polygon.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/squared_distance.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/squared_distance_to_element.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/squared_exponential_kernel.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/subdivide.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/subdivide_quad.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/tip_angles.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/tip_angles_intrinsic.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/torus.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/traverse_aabbtree.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/triangle_triangle_adjacency.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/triangle_triangle_distance.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/upper_envelope.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/volume.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/winding_number.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      copying src/gpytoolbox/write_mesh.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox
      creating build/lib.linux-x86_64-cpython-312/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/__init__.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/do_meshes_intersect.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/lazy_cage.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/mesh_boolean.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/swept_volume.py -> build/lib.linux-x86_64-cpython-312/gpytoolbox/copyleft
      running build_ext
      CMake Warning:
        Ignoring extra path from command line:
      
         "/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478"
      
      
      CMake Error: The source directory "/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      Running cmake configure command: cmake /tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478/build/lib.linux-x86_64-cpython-312 -DPYTHON_EXECUTABLE=/root/miniconda3/bin/python -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      Traceback (most recent call last):
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', metadata_directory])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 422, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 128, in <module>
        File "<string>", line 106, in main
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 991, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 407, in run
          self.run_command("build")
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 991, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 991, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-f8yw1g0s/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 41, in run
        File "<string>", line 84, in build_extension
        File "/root/miniconda3/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478/build/lib.linux-x86_64-cpython-312', '-DPYTHON_EXECUTABLE=/root/miniconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gpytoolbox
  Building wheel for texture_baker (setup.py) ... done
  Created wheel for texture_baker: filename=texture_baker-0.0.1-cp312-cp312-linux_x86_64.whl size=330223 sha256=eab142ea4acdb07f92cea6a9535bdaa21781ec64c5bf0aaa4bd62dc7b654499e
  Stored in directory: /tmp/pip-ephem-wheel-cache-b0ksicfy/wheels/40/81/44/46a9a60af5370f9d3d6ee24618d1b7b5d5810ac9b3c2175caf
  Building wheel for uv_unwrapper (setup.py) ... done
  Created wheel for uv_unwrapper: filename=uv_unwrapper-0.0.1-cp312-cp312-linux_x86_64.whl size=102883 sha256=40962bced6b22d54d52101e64021a44ea4ddb1a75837c33390467254b381855e
  Stored in directory: /tmp/pip-ephem-wheel-cache-b0ksicfy/wheels/77/ef/e9/855603cdbc732ebc83b2a9dafd10636b34d71fc7d6e7a35a7b
Successfully built texture_baker uv_unwrapper
Failed to build gpytoolbox
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (gpytoolbox)`

**Comment by dedoogong** [comment]
same here. and slang.h no file found error too

**Comment by peachyhead** [comment]
same problem
m1 pro
macOS 15.0.1

**Comment by akumarm642** [comment]
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
first run this command that install the torch for windows then
`pip install -r requirements.txt`
run this command
For other OS: https://pytorch.org/get-started/locally/

**Comment by peachyhead** [comment]
nope, not helped

Main issue here as I see:

CMake Error: The source directory "/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  Running cmake configure command: cmake /tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-zqflse84/gpytoolbox_cd885e9e3d774cccaf487759d5fa3478/build/lib.linux-x86_64-cpython-312 -DPYTHON_EXECUTABLE=/root/miniconda3/bin/python -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

**Comment by rcmz** [comment]
Same issue on Manjaro

**Comment by pierre1618** [comment]
I solved this by replacing "gpytoolbox==0.2.0" by  "gpytoolbox==0.3.3" in the readme file

**Comment by laftho** [comment]
gpytoolbox==0.3.3 worked for me as well, thanks @pierre1618

**Comment by 3vi1** [comment]
This issue seems to have returned?  Just tried to install on Linux today with Python3.13 and get the same error about the missing CMakeList.txt.
